### PR TITLE
simplify git push with tags

### PR DESCRIPTION
**Pull request by matmuchrapna**
There is no need to run push twice, 'cause you can run it with tags flag first time

### CODE REVIEW

**Comment by badsyntax** [comment]
I'm not convinced this is correct.

When running: `npm version patch`, it's going to add a new commit (change to package.json) as well as create a new tag.
When running `git push --tags` after updating the version, it's not going to push that commit. I think `git push --follow-tags` is what we're after if we want to only use one git command.

**Comment by matmuchrapna** [comment]
> When running git push --tags after updating the version, it's not going to push that commit. 

— nope. Actually it's going to. Due to [docs](http://linux.die.net/man/1/git-push):

> --tags
>     All refs under refs/tags are pushed, in addition to refspecs explicitly listed on the command line. 

So `git push --tags` is equal to `git push && git push --tags`, isn't it?

PS. We are doing this way in developing our internal generator, and it works well. But anyway, maybe I'm wrong.

**Comment by matmuchrapna** [comment]
Seems, you are about --follow-tags, and I'm not. sorry. https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.3.txt#L155-L156

**Comment by badsyntax** [comment]
Thanks for clarifying and letting me know.

**Pull request closed without merging**
